# Generated by Django 4.2.6 on 2024-01-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_todo_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='upload',
            field=models.ImageField(upload_to='todo/uploads/media/'),
        ),
    ]
