# Generated by Django 4.2.6 on 2024-01-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_todo_item_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='item_image_url',
            field=models.TextField(default=None),
        ),
    ]
