# Generated by Django 4.2.6 on 2024-01-18 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_alter_todo_item_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='item_image_url',
        ),
    ]
