# Generated by Django 4.2.6 on 2024-01-18 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0011_remove_todo_item_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='upload_base64',
            field=models.TextField(blank=True, null=True),
        ),
    ]
