# Generated by Django 4.2.6 on 2024-01-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_todo_upload_base64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='upload',
            field=models.ImageField(default='default.jpg', upload_to='todo/uploads/media/'),
        ),
    ]
