# Generated by Django 4.2.6 on 2024-01-19 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0016_remove_todo_upload_base64'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='upload',
        ),
    ]
