# Generated by Django 4.2.6 on 2024-01-19 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0017_remove_todo_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='upload',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
