# Generated by Django 4.2.6 on 2024-01-19 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0018_todo_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='upload',
            field=models.ImageField(default=False, upload_to=''),
        ),
    ]
