# Generated by Django 4.2.6 on 2024-01-19 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0022_alter_todo_body_alter_todo_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='upload',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
