# Generated by Django 4.2.6 on 2024-01-19 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0025_alter_todo_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='upload',
            field=models.ImageField(blank=True, default='default', null=True, upload_to=''),
        ),
    ]
